/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class extapi_ExtApi */

#ifndef _Included_extapi_ExtApi
#define _Included_extapi_ExtApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     extapi_ExtApi
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_extapi_ExtApi_init
  (JNIEnv *, jobject);

/*
 * Class:     extapi_ExtApi
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_extapi_ExtApi_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
