/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_esa_beam_extapi_COperator */

#ifndef _Included_org_esa_beam_extapi_COperator
#define _Included_org_esa_beam_extapi_COperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_esa_beam_extapi_COperator
 * Method:    computeTileNative
 * Signature: (IIIIIILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_esa_beam_extapi_COperator_computeTileNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_esa_beam_extapi_COperator
 * Method:    computeTileStackNative
 * Signature: (I[IIIII[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_esa_beam_extapi_COperator_computeTileStackNative
  (JNIEnv *, jobject, jint, jintArray, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     org_esa_beam_extapi_COperator
 * Method:    initializeNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_esa_beam_extapi_COperator_initializeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_esa_beam_extapi_COperator
 * Method:    disposeNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_esa_beam_extapi_COperator_disposeNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
