/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_esa_beam_extapi_PythonApi */

#ifndef _Included_org_esa_beam_extapi_PythonApi
#define _Included_org_esa_beam_extapi_PythonApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_esa_beam_extapi_PythonApi
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esa_beam_extapi_PythonApi_init
  (JNIEnv *, jobject);

/*
 * Class:     org_esa_beam_extapi_PythonApi
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_esa_beam_extapi_PythonApi_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
